/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccountAccessEvents: () => import('#controllers/account_access_events_controller'),
  Accounts: () => import('#controllers/accounts_controller'),
  BaseUnits: () => import('#controllers/base_units_controller'),
  CatalogueCategories: () => import('#controllers/catalogue_categories_controller'),
  CatalogueItems: () => import('#controllers/catalogue_items_controller'),
  CategoryAttributeChoices: () => import('#controllers/category_attribute_choices_controller'),
  CategoryAttributes: () => import('#controllers/category_attributes_controller'),
  Delegations: () => import('#controllers/delegations_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  OrganizationalUnits: () => import('#controllers/organizational_units_controller'),
  PasswordResets: () => import('#controllers/password_resets_controller'),
  PasswordSetups: () => import('#controllers/password_setups_controller'),
  Permissions: () => import('#controllers/permissions_controller'),
  PhysicalLocations: () => import('#controllers/physical_locations_controller'),
  RoleAssignments: () => import('#controllers/role_assignments_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
}
