/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AccessEventTransformer from '#transformers/access_event_transformer'
import type AccountTransformer from '#transformers/account_transformer'
import type BaseUnitTransformer from '#transformers/base_unit_transformer'
import type BaseUnitVersionTransformer from '#transformers/base_unit_version_transformer'
import type CatalogueCategoryTransformer from '#transformers/catalogue_category_transformer'
import type CatalogueCategoryVersionTransformer from '#transformers/catalogue_category_version_transformer'
import type CategoryAttributeChoiceTransformer from '#transformers/category_attribute_choice_transformer'
import type CategoryAttributeChoiceVersionTransformer from '#transformers/category_attribute_choice_version_transformer'
import type CategoryAttributeTransformer from '#transformers/category_attribute_transformer'
import type CategoryAttributeVersionTransformer from '#transformers/category_attribute_version_transformer'
import type CurrentAccountTransformer from '#transformers/current_account_transformer'
import type DelegationProposalOptionsTransformer from '#transformers/delegation_proposal_options_transformer'
import type DelegationTransformer from '#transformers/delegation_transformer'
import type OrganizationalUnitTransformer from '#transformers/organizational_unit_transformer'
import type OrganizationalUnitVersionTransformer from '#transformers/organizational_unit_version_transformer'
import type PermissionTransformer from '#transformers/permission_transformer'
import type PhysicalLocationTransformer from '#transformers/physical_location_transformer'
import type PhysicalLocationVersionTransformer from '#transformers/physical_location_version_transformer'
import type RoleAssignmentTransformer from '#transformers/role_assignment_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type RoleVersionTransformer from '#transformers/role_version_transformer'

export namespace Data {
  export type AccessEvent = InferData<AccessEventTransformer>
  export namespace AccessEvent {
    export type Variants = InferVariants<AccessEventTransformer>
  }
  export type Account = InferData<AccountTransformer>
  export namespace Account {
    export type Variants = InferVariants<AccountTransformer>
  }
  export type BaseUnit = InferData<BaseUnitTransformer>
  export namespace BaseUnit {
    export type Variants = InferVariants<BaseUnitTransformer>
  }
  export type BaseUnitVersion = InferData<BaseUnitVersionTransformer>
  export namespace BaseUnitVersion {
    export type Variants = InferVariants<BaseUnitVersionTransformer>
  }
  export type CatalogueCategory = InferData<CatalogueCategoryTransformer>
  export namespace CatalogueCategory {
    export type Variants = InferVariants<CatalogueCategoryTransformer>
  }
  export type CatalogueCategoryVersion = InferData<CatalogueCategoryVersionTransformer>
  export namespace CatalogueCategoryVersion {
    export type Variants = InferVariants<CatalogueCategoryVersionTransformer>
  }
  export type CategoryAttributeChoice = InferData<CategoryAttributeChoiceTransformer>
  export namespace CategoryAttributeChoice {
    export type Variants = InferVariants<CategoryAttributeChoiceTransformer>
  }
  export type CategoryAttributeChoiceVersion = InferData<CategoryAttributeChoiceVersionTransformer>
  export namespace CategoryAttributeChoiceVersion {
    export type Variants = InferVariants<CategoryAttributeChoiceVersionTransformer>
  }
  export type CategoryAttribute = InferData<CategoryAttributeTransformer>
  export namespace CategoryAttribute {
    export type Variants = InferVariants<CategoryAttributeTransformer>
  }
  export type CategoryAttributeVersion = InferData<CategoryAttributeVersionTransformer>
  export namespace CategoryAttributeVersion {
    export type Variants = InferVariants<CategoryAttributeVersionTransformer>
  }
  export type CurrentAccount = InferData<CurrentAccountTransformer>
  export namespace CurrentAccount {
    export type Variants = InferVariants<CurrentAccountTransformer>
  }
  export type DelegationProposalOptions = InferData<DelegationProposalOptionsTransformer>
  export namespace DelegationProposalOptions {
    export type Variants = InferVariants<DelegationProposalOptionsTransformer>
  }
  export type Delegation = InferData<DelegationTransformer>
  export namespace Delegation {
    export type Variants = InferVariants<DelegationTransformer>
  }
  export type OrganizationalUnit = InferData<OrganizationalUnitTransformer>
  export namespace OrganizationalUnit {
    export type Variants = InferVariants<OrganizationalUnitTransformer>
  }
  export type OrganizationalUnitVersion = InferData<OrganizationalUnitVersionTransformer>
  export namespace OrganizationalUnitVersion {
    export type Variants = InferVariants<OrganizationalUnitVersionTransformer>
  }
  export type Permission = InferData<PermissionTransformer>
  export namespace Permission {
    export type Variants = InferVariants<PermissionTransformer>
  }
  export type PhysicalLocation = InferData<PhysicalLocationTransformer>
  export namespace PhysicalLocation {
    export type Variants = InferVariants<PhysicalLocationTransformer>
  }
  export type PhysicalLocationVersion = InferData<PhysicalLocationVersionTransformer>
  export namespace PhysicalLocationVersion {
    export type Variants = InferVariants<PhysicalLocationVersionTransformer>
  }
  export type RoleAssignment = InferData<RoleAssignmentTransformer>
  export namespace RoleAssignment {
    export type Variants = InferVariants<RoleAssignmentTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type RoleVersion = InferData<RoleVersionTransformer>
  export namespace RoleVersion {
    export type Variants = InferVariants<RoleVersionTransformer>
  }
}
