/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AccountRoleAssignmentTransformer from '#transformers/account_role_assignment_transformer'
import type AccountTransformer from '#transformers/account_transformer'
import type CurrentAccountTransformer from '#transformers/current_account_transformer'
import type OrganizationalUnitTransformer from '#transformers/organizational_unit_transformer'
import type OrganizationalUnitVersionTransformer from '#transformers/organizational_unit_version_transformer'

export namespace Data {
  export type AccountRoleAssignment = InferData<AccountRoleAssignmentTransformer>
  export namespace AccountRoleAssignment {
    export type Variants = InferVariants<AccountRoleAssignmentTransformer>
  }
  export type Account = InferData<AccountTransformer>
  export namespace Account {
    export type Variants = InferVariants<AccountTransformer>
  }
  export type CurrentAccount = InferData<CurrentAccountTransformer>
  export namespace CurrentAccount {
    export type Variants = InferVariants<CurrentAccountTransformer>
  }
  export type OrganizationalUnit = InferData<OrganizationalUnitTransformer>
  export namespace OrganizationalUnit {
    export type Variants = InferVariants<OrganizationalUnitTransformer>
  }
  export type OrganizationalUnitVersion = InferData<OrganizationalUnitVersionTransformer>
  export namespace OrganizationalUnitVersion {
    export type Variants = InferVariants<OrganizationalUnitVersionTransformer>
  }
}
