/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AccessEventTransformer from '#transformers/access_event_transformer'
import type AccountTransformer from '#transformers/account_transformer'
import type BaseUnitTransformer from '#transformers/base_unit_transformer'
import type BaseUnitVersionTransformer from '#transformers/base_unit_version_transformer'
import type CatalogueCategoryMergePreviewTransformer from '#transformers/catalogue_category_merge_preview_transformer'
import type CatalogueCategoryTransformer from '#transformers/catalogue_category_transformer'
import type CatalogueCategoryVersionTransformer from '#transformers/catalogue_category_version_transformer'
import type CatalogueItemReviewTransformer from '#transformers/catalogue_item_review_transformer'
import type CatalogueItemTransformer from '#transformers/catalogue_item_transformer'
import type CatalogueItemVersionTransformer from '#transformers/catalogue_item_version_transformer'
import type CurrentAccountTransformer from '#transformers/current_account_transformer'
import type DelegationProposalOptionsTransformer from '#transformers/delegation_proposal_options_transformer'
import type DelegationTransformer from '#transformers/delegation_transformer'
import type OrganizationalUnitTransformer from '#transformers/organizational_unit_transformer'
import type OrganizationalUnitVersionTransformer from '#transformers/organizational_unit_version_transformer'
import type PermissionTransformer from '#transformers/permission_transformer'
import type PhysicalLocationTransformer from '#transformers/physical_location_transformer'
import type PhysicalLocationVersionTransformer from '#transformers/physical_location_version_transformer'
import type RoleAssignmentTransformer from '#transformers/role_assignment_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type RoleVersionTransformer from '#transformers/role_version_transformer'

export namespace Data {
  export type AccessEvent = InferData<AccessEventTransformer>
  export namespace AccessEvent {
    export type Variants = InferVariants<AccessEventTransformer>
  }
  export type Account = InferData<AccountTransformer>
  export namespace Account {
    export type Variants = InferVariants<AccountTransformer>
  }
  export type BaseUnit = InferData<BaseUnitTransformer>
  export namespace BaseUnit {
    export type Variants = InferVariants<BaseUnitTransformer>
  }
  export type BaseUnitVersion = InferData<BaseUnitVersionTransformer>
  export namespace BaseUnitVersion {
    export type Variants = InferVariants<BaseUnitVersionTransformer>
  }
  export type CatalogueCategoryMergePreview = InferData<CatalogueCategoryMergePreviewTransformer>
  export namespace CatalogueCategoryMergePreview {
    export type Variants = InferVariants<CatalogueCategoryMergePreviewTransformer>
  }
  export type CatalogueCategory = InferData<CatalogueCategoryTransformer>
  export namespace CatalogueCategory {
    export type Variants = InferVariants<CatalogueCategoryTransformer>
  }
  export type CatalogueCategoryVersion = InferData<CatalogueCategoryVersionTransformer>
  export namespace CatalogueCategoryVersion {
    export type Variants = InferVariants<CatalogueCategoryVersionTransformer>
  }
  export type CatalogueItemReview = InferData<CatalogueItemReviewTransformer>
  export namespace CatalogueItemReview {
    export type Variants = InferVariants<CatalogueItemReviewTransformer>
  }
  export type CatalogueItem = InferData<CatalogueItemTransformer>
  export namespace CatalogueItem {
    export type Variants = InferVariants<CatalogueItemTransformer>
  }
  export type CatalogueItemVersion = InferData<CatalogueItemVersionTransformer>
  export namespace CatalogueItemVersion {
    export type Variants = InferVariants<CatalogueItemVersionTransformer>
  }
  export type CurrentAccount = InferData<CurrentAccountTransformer>
  export namespace CurrentAccount {
    export type Variants = InferVariants<CurrentAccountTransformer>
  }
  export type DelegationProposalOptions = InferData<DelegationProposalOptionsTransformer>
  export namespace DelegationProposalOptions {
    export type Variants = InferVariants<DelegationProposalOptionsTransformer>
  }
  export type Delegation = InferData<DelegationTransformer>
  export namespace Delegation {
    export type Variants = InferVariants<DelegationTransformer>
  }
  export type OrganizationalUnit = InferData<OrganizationalUnitTransformer>
  export namespace OrganizationalUnit {
    export type Variants = InferVariants<OrganizationalUnitTransformer>
  }
  export type OrganizationalUnitVersion = InferData<OrganizationalUnitVersionTransformer>
  export namespace OrganizationalUnitVersion {
    export type Variants = InferVariants<OrganizationalUnitVersionTransformer>
  }
  export type Permission = InferData<PermissionTransformer>
  export namespace Permission {
    export type Variants = InferVariants<PermissionTransformer>
  }
  export type PhysicalLocation = InferData<PhysicalLocationTransformer>
  export namespace PhysicalLocation {
    export type Variants = InferVariants<PhysicalLocationTransformer>
  }
  export type PhysicalLocationVersion = InferData<PhysicalLocationVersionTransformer>
  export namespace PhysicalLocationVersion {
    export type Variants = InferVariants<PhysicalLocationVersionTransformer>
  }
  export type RoleAssignment = InferData<RoleAssignmentTransformer>
  export namespace RoleAssignment {
    export type Variants = InferVariants<RoleAssignmentTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type RoleVersion = InferData<RoleVersionTransformer>
  export namespace RoleVersion {
    export type Variants = InferVariants<RoleVersionTransformer>
  }
}
