/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessEventSchema extends BaseModel {
  static $columns = ['actorAccountId', 'actorType', 'createdAt', 'eventType', 'id', 'identifierFingerprint', 'metadata', 'reason', 'requestId', 'requestIp', 'targetId', 'targetType'] as const
  $columns = AccessEventSchema.$columns
  @column()
  declare actorAccountId: string | null
  @column()
  declare actorType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identifierFingerprint: string | null
  @column()
  declare metadata: any
  @column()
  declare reason: string | null
  @column()
  declare requestId: string | null
  @column()
  declare requestIp: string | null
  @column()
  declare targetId: string | null
  @column()
  declare targetType: string
}

export class BaseUnitVersionSchema extends BaseModel {
  static $columns = ['archivedAt', 'authorizationDelegationId', 'authorizationRoleAssignmentId', 'baseUnitId', 'changeKind', 'changedByAccountId', 'createdAt', 'effectiveFrom', 'effectiveTo', 'id', 'kind', 'name', 'permissionKey', 'precision', 'reason', 'resolvedScopeOrganizationalUnitId', 'symbol', 'version'] as const
  $columns = BaseUnitVersionSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare authorizationDelegationId: string | null
  @column()
  declare authorizationRoleAssignmentId: string
  @column()
  declare baseUnitId: string
  @column()
  declare changeKind: string
  @column()
  declare changedByAccountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare name: string
  @column()
  declare permissionKey: string
  @column()
  declare precision: number
  @column()
  declare reason: string
  @column()
  declare resolvedScopeOrganizationalUnitId: string
  @column()
  declare symbol: string
  @column()
  declare version: number
}

export class BaseUnitSchema extends BaseModel {
  static $columns = ['archivedAt', 'createdAt', 'firstUsedAt', 'id', 'kind', 'name', 'precision', 'symbol', 'updatedAt'] as const
  $columns = BaseUnitSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare firstUsedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare name: string
  @column()
  declare precision: number
  @column()
  declare symbol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatalogueCategorySchema extends BaseModel {
  static $columns = ['archivedAt', 'createdAt', 'description', 'id', 'mergedIntoCategoryId', 'name', 'parentId', 'updatedAt'] as const
  $columns = CatalogueCategorySchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mergedIntoCategoryId: string | null
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatalogueCategoryVersionSchema extends BaseModel {
  static $columns = ['archivedAt', 'authorizationDelegationId', 'authorizationRoleAssignmentId', 'catalogueCategoryId', 'changeKind', 'changedByAccountId', 'createdAt', 'description', 'effectiveFrom', 'effectiveTo', 'id', 'mergedIntoCategoryId', 'name', 'parentId', 'permissionKey', 'reason', 'resolvedScopeOrganizationalUnitId', 'version'] as const
  $columns = CatalogueCategoryVersionSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare authorizationDelegationId: string | null
  @column()
  declare authorizationRoleAssignmentId: string
  @column()
  declare catalogueCategoryId: string
  @column()
  declare changeKind: string
  @column()
  declare changedByAccountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mergedIntoCategoryId: string | null
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column()
  declare permissionKey: string
  @column()
  declare reason: string
  @column()
  declare resolvedScopeOrganizationalUnitId: string
  @column()
  declare version: number
}

export class CatalogueItemKeywordSchema extends BaseModel {
  static $columns = ['catalogueItemId', 'createdAt', 'displayOrder', 'id', 'keyword', 'normalizedKeyword', 'updatedAt'] as const
  $columns = CatalogueItemKeywordSchema.$columns
  @column()
  declare catalogueItemId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayOrder: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyword: string
  @column()
  declare normalizedKeyword: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatalogueItemReviewCandidateSchema extends BaseModel {
  static $columns = ['candidateCatalogueItemId', 'catalogueItemVersionId', 'confirmationReason', 'createdAt', 'displayOrder', 'id', 'primaryMatchKind'] as const
  $columns = CatalogueItemReviewCandidateSchema.$columns
  @column()
  declare candidateCatalogueItemId: string
  @column()
  declare catalogueItemVersionId: string
  @column()
  declare confirmationReason: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayOrder: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare primaryMatchKind: string
}

export class CatalogueItemVersionKeywordSchema extends BaseModel {
  static $columns = ['catalogueItemVersionId', 'createdAt', 'displayOrder', 'id', 'keyword', 'normalizedKeyword'] as const
  $columns = CatalogueItemVersionKeywordSchema.$columns
  @column()
  declare catalogueItemVersionId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayOrder: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyword: string
  @column()
  declare normalizedKeyword: string
}

export class CatalogueItemVersionSchema extends BaseModel {
  static $columns = ['archivedAt', 'authorizationDelegationId', 'authorizationRoleAssignmentId', 'baseUnitId', 'catalogueCategoryId', 'catalogueCode', 'catalogueItemId', 'changeKind', 'changedByAccountId', 'createdAt', 'description', 'effectiveFrom', 'effectiveTo', 'id', 'identificationStatus', 'inventorySemanticsLockedAt', 'name', 'normalizedName', 'permissionKey', 'reason', 'resolvedScopeOrganizationalUnitId', 'stockType', 'trackingMethod', 'version'] as const
  $columns = CatalogueItemVersionSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare authorizationDelegationId: string | null
  @column()
  declare authorizationRoleAssignmentId: string
  @column()
  declare baseUnitId: string
  @column()
  declare catalogueCategoryId: string
  @column()
  declare catalogueCode: string
  @column()
  declare catalogueItemId: string
  @column()
  declare changeKind: string
  @column()
  declare changedByAccountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identificationStatus: string
  @column.dateTime()
  declare inventorySemanticsLockedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare normalizedName: string
  @column()
  declare permissionKey: string
  @column()
  declare reason: string
  @column()
  declare resolvedScopeOrganizationalUnitId: string
  @column()
  declare stockType: string
  @column()
  declare trackingMethod: string
  @column()
  declare version: number
}

export class CatalogueItemSchema extends BaseModel {
  static $columns = ['archivedAt', 'baseUnitId', 'catalogueCategoryId', 'catalogueCode', 'createdAt', 'description', 'id', 'identificationStatus', 'inventorySemanticsLockedAt', 'name', 'normalizedName', 'stockType', 'trackingMethod', 'updatedAt'] as const
  $columns = CatalogueItemSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare baseUnitId: string
  @column()
  declare catalogueCategoryId: string
  @column()
  declare catalogueCode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identificationStatus: string
  @column.dateTime()
  declare inventorySemanticsLockedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare normalizedName: string
  @column()
  declare stockType: string
  @column()
  declare trackingMethod: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CentralStoreContextVersionSchema extends BaseModel {
  static $columns = ['configuredByAccountId', 'createdAt', 'custodialOrganizationalUnitId', 'effectiveFrom', 'id', 'physicalLocationId', 'reason', 'version'] as const
  $columns = CentralStoreContextVersionSchema.$columns
  @column()
  declare configuredByAccountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare custodialOrganizationalUnitId: string
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare physicalLocationId: string
  @column()
  declare reason: string
  @column()
  declare version: number
}

export class DelegationAssignmentSchema extends BaseModel {
  static $columns = ['createdAt', 'delegationId', 'id', 'sourceAssignmentId'] as const
  $columns = DelegationAssignmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delegationId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare sourceAssignmentId: string
}

export class DelegationResponseSchema extends BaseModel {
  static $columns = ['createdAt', 'delegationId', 'id', 'kind', 'reason', 'respondedByAccountId'] as const
  $columns = DelegationResponseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delegationId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare reason: string | null
  @column()
  declare respondedByAccountId: string
}

export class DelegationTerminationSchema extends BaseModel {
  static $columns = ['createdAt', 'delegationId', 'effectiveAt', 'id', 'kind', 'reason', 'terminatedByAccountId'] as const
  $columns = DelegationTerminationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delegationId: string
  @column.dateTime()
  declare effectiveAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare reason: string
  @column()
  declare terminatedByAccountId: string
}

export class DelegationSchema extends BaseModel {
  static $columns = ['createdAt', 'delegateAccountId', 'delegatorAccountId', 'expiresAt', 'id', 'reason', 'startsAt'] as const
  $columns = DelegationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delegateAccountId: string
  @column()
  declare delegatorAccountId: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reason: string
  @column.dateTime()
  declare startsAt: DateTime
}

export class LockSchema extends BaseModel {
  static $columns = ['expiration', 'key', 'owner'] as const
  $columns = LockSchema.$columns
  @column()
  declare expiration: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare owner: string
}

export class OrganizationalUnitVersionSchema extends BaseModel {
  static $columns = ['archivedAt', 'changedByAccountId', 'createdAt', 'effectiveFrom', 'effectiveTo', 'id', 'name', 'organizationalUnitId', 'parentId', 'reason', 'unitType', 'version'] as const
  $columns = OrganizationalUnitVersionSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare changedByAccountId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare organizationalUnitId: string
  @column()
  declare parentId: string | null
  @column()
  declare reason: string
  @column()
  declare unitType: string
  @column()
  declare version: number
}

export class OrganizationalUnitSchema extends BaseModel {
  static $columns = ['archivedAt', 'createdAt', 'id', 'name', 'parentId', 'unitType', 'updatedAt'] as const
  $columns = OrganizationalUnitSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column()
  declare unitType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PasswordResetChallengeSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'expiresAt', 'id', 'purpose', 'requestId', 'requestIp', 'resetVersion'] as const
  $columns = PasswordResetChallengeSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare purpose: string
  @column()
  declare requestId: string | null
  @column()
  declare requestIp: string | null
  @column()
  declare resetVersion: bigint | number
}

export class PasswordResetRedemptionSchema extends BaseModel {
  static $columns = ['accountId', 'challengeId', 'createdAt', 'requestId', 'requestIp'] as const
  $columns = PasswordResetRedemptionSchema.$columns
  @column()
  declare accountId: string
  @column({ isPrimary: true })
  declare challengeId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare requestId: string | null
  @column()
  declare requestIp: string | null
}

export class PersonSchema extends BaseModel {
  static $columns = ['archivedAt', 'createdAt', 'displayName', 'id', 'primaryEmail', 'primaryEmailVerifiedAt', 'staffNumber', 'updatedAt'] as const
  $columns = PersonSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare primaryEmail: string | null
  @column.dateTime()
  declare primaryEmailVerifiedAt: DateTime | null
  @column()
  declare staffNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'customRoleAssignable', 'description', 'key'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customRoleAssignable: boolean
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare key: string
}

export class PhysicalLocationVersionSchema extends BaseModel {
  static $columns = ['archivedAt', 'changedByAccountId', 'createdAt', 'effectiveFrom', 'effectiveTo', 'id', 'name', 'parentId', 'physicalLocationId', 'reason', 'version'] as const
  $columns = PhysicalLocationVersionSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare changedByAccountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column()
  declare physicalLocationId: string
  @column()
  declare reason: string
  @column()
  declare version: number
}

export class PhysicalLocationSchema extends BaseModel {
  static $columns = ['archivedAt', 'createdAt', 'id', 'name', 'parentId', 'updatedAt'] as const
  $columns = PhysicalLocationSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'dedupAt', 'dedupId', 'dedupTtl', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare dedupAt: bigint | number | null
  @column()
  declare dedupId: string | null
  @column()
  declare dedupTtl: bigint | number | null
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RoleAssignmentTerminationSchema extends BaseModel {
  static $columns = ['assignmentId', 'createdAt', 'effectiveAt', 'id', 'kind', 'reason', 'replacementAssignmentId', 'terminatedByAccountId'] as const
  $columns = RoleAssignmentTerminationSchema.$columns
  @column()
  declare assignmentId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare reason: string
  @column()
  declare replacementAssignmentId: string | null
  @column()
  declare terminatedByAccountId: string
}

export class RoleAssignmentSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'expiresAt', 'grantedByAccountId', 'id', 'reason', 'roleVersionId', 'scopeMode', 'scopeOrgUnitId', 'startsAt'] as const
  $columns = RoleAssignmentSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare grantedByAccountId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reason: string
  @column()
  declare roleVersionId: string
  @column()
  declare scopeMode: string
  @column()
  declare scopeOrgUnitId: string
  @column.dateTime()
  declare startsAt: DateTime
}

export class RoleVersionPermissionSchema extends BaseModel {
  static $columns = ['permissionKey', 'roleVersionId'] as const
  $columns = RoleVersionPermissionSchema.$columns
  @column()
  declare permissionKey: string
  @column({ isPrimary: true })
  declare roleVersionId: string
}

export class RoleVersionSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByAccountId', 'id', 'reason', 'roleId', 'version'] as const
  $columns = RoleVersionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByAccountId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reason: string
  @column()
  declare roleId: string
  @column()
  declare version: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['archivedAt', 'createdAt', 'id', 'key', 'name', 'systemManaged', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare name: string
  @column()
  declare systemManaged: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'credentialVersion', 'email', 'id', 'lastLoginAt', 'password', 'passwordResetVersion', 'personId', 'status', 'updatedAt'] as const
  $columns = UserAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credentialVersion: bigint | number
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare passwordResetVersion: bigint | number
  @column()
  declare personId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
