/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessEventSchema extends BaseModel {
  static $columns = ['actorAccountId', 'actorType', 'createdAt', 'eventType', 'id', 'identifierFingerprint', 'metadata', 'reason', 'requestId', 'requestIp', 'targetId', 'targetType'] as const
  $columns = AccessEventSchema.$columns
  @column()
  declare actorAccountId: string | null
  @column()
  declare actorType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identifierFingerprint: string | null
  @column()
  declare metadata: any
  @column()
  declare reason: string | null
  @column()
  declare requestId: string | null
  @column()
  declare requestIp: string | null
  @column()
  declare targetId: string | null
  @column()
  declare targetType: string
}

export class LockSchema extends BaseModel {
  static $columns = ['expiration', 'key', 'owner'] as const
  $columns = LockSchema.$columns
  @column()
  declare expiration: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare owner: string
}

export class OrganizationalUnitVersionSchema extends BaseModel {
  static $columns = ['archivedAt', 'changedByAccountId', 'createdAt', 'effectiveFrom', 'effectiveTo', 'id', 'name', 'organizationalUnitId', 'parentId', 'reason', 'unitType', 'version'] as const
  $columns = OrganizationalUnitVersionSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare changedByAccountId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare organizationalUnitId: string
  @column()
  declare parentId: string | null
  @column()
  declare reason: string
  @column()
  declare unitType: string
  @column()
  declare version: number
}

export class OrganizationalUnitSchema extends BaseModel {
  static $columns = ['archivedAt', 'createdAt', 'id', 'name', 'parentId', 'unitType', 'updatedAt'] as const
  $columns = OrganizationalUnitSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column()
  declare unitType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PasswordResetChallengeSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'expiresAt', 'id', 'purpose', 'requestId', 'requestIp', 'resetVersion'] as const
  $columns = PasswordResetChallengeSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare purpose: string
  @column()
  declare requestId: string | null
  @column()
  declare requestIp: string | null
  @column()
  declare resetVersion: bigint | number
}

export class PasswordResetRedemptionSchema extends BaseModel {
  static $columns = ['accountId', 'challengeId', 'createdAt', 'requestId', 'requestIp'] as const
  $columns = PasswordResetRedemptionSchema.$columns
  @column()
  declare accountId: string
  @column({ isPrimary: true })
  declare challengeId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare requestId: string | null
  @column()
  declare requestIp: string | null
}

export class PersonSchema extends BaseModel {
  static $columns = ['archivedAt', 'createdAt', 'displayName', 'id', 'primaryEmail', 'primaryEmailVerifiedAt', 'staffNumber', 'updatedAt'] as const
  $columns = PersonSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare primaryEmail: string | null
  @column.dateTime()
  declare primaryEmailVerifiedAt: DateTime | null
  @column()
  declare staffNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'key'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare key: string
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'dedupAt', 'dedupId', 'dedupTtl', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare dedupAt: bigint | number | null
  @column()
  declare dedupId: string | null
  @column()
  declare dedupTtl: bigint | number | null
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RoleAssignmentSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'expiresAt', 'grantedByAccountId', 'id', 'reason', 'roleVersionId', 'scopeMode', 'scopeOrgUnitId', 'startsAt'] as const
  $columns = RoleAssignmentSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare grantedByAccountId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reason: string
  @column()
  declare roleVersionId: string
  @column()
  declare scopeMode: string
  @column()
  declare scopeOrgUnitId: string
  @column.dateTime()
  declare startsAt: DateTime
}

export class RoleVersionPermissionSchema extends BaseModel {
  static $columns = ['permissionKey', 'roleVersionId'] as const
  $columns = RoleVersionPermissionSchema.$columns
  @column()
  declare permissionKey: string
  @column({ isPrimary: true })
  declare roleVersionId: string
}

export class RoleVersionSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByAccountId', 'id', 'reason', 'roleId', 'version'] as const
  $columns = RoleVersionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByAccountId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reason: string
  @column()
  declare roleId: string
  @column()
  declare version: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['archivedAt', 'createdAt', 'id', 'key', 'name', 'systemManaged'] as const
  $columns = RoleSchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare name: string
  @column()
  declare systemManaged: boolean
}

export class UserAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'credentialVersion', 'email', 'id', 'lastLoginAt', 'password', 'passwordResetVersion', 'personId', 'status', 'updatedAt'] as const
  $columns = UserAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credentialVersion: bigint | number
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare passwordResetVersion: bigint | number
  @column()
  declare personId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
